version: "3"
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dokerfile
    container_name: app
    ports:
      - 3000:8000
    volumes:
      - ./app:/app
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_pruebas
    ports:
      - 2000:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=1234
